# Site settings
title: REMO
description: |
  Remo es una compañía dedicada a generar contenidos, realizar ideas y trabajar en colaboración.
url: "https://remoaudiovisual.github.io/" # the base hostname & protocol for this site
baseurl: "" # the subpath of your site, e.g. /blog
            # Note you'll have to move your robots.txt to the root if you want it used.
            # And list multiple sitemaps if there are other subdirectories you want indexed
            # besides this blog.
lang: en-us # used in HTML lang attributes

# on landing page

# all text
greeting:
  sub-para1: Remo es una compañía dedicada a generar contenidos, realizar ideas y trabajar en colaboración.
  sub-para2: Desde el 2017 hemos trabajado de forma colaborativa entre profesionales del arte, cine, diseño y publicidad, abordando los proyectos desde su génesis hasta su finalización.
  sub-para3: creatividad
  sub-para4: rodaje
  sub-para5: postproducción
  link-text: TRABAJOS
  link-url: https://www.vimeo.com/remoaudiovisual/

  # logo
  logo: /assets/img/remoaudiovisual_logo.png
  logo-alt: remo audio visual logo


# Build settings
markdown: kramdown
sass:
  style: compressed
exclude: ['README.md']

footer-links:
email: Contacto: felipe@remoaudiovisual.cl / joaquin@remoaudiovisual.cl
